artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  local_data_path: [artifacts/data_ingestion/creditcard.csv, artifacts/data_ingestion/default.csv]

data_validation:
  root_dir: artifacts/data_validation
  local_data_path: [artifacts/data_ingestion/creditcard.csv, artifacts/data_ingestion/default.csv]
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: [artifacts/data_ingestion/creditcard.csv, artifacts/data_ingestion/default.csv]
  preprocessed_data_path: [artifacts/data_transformation/fraudulent_transection, artifacts/data_transformation/default_on_payment]
  preprocessor_name: preprocessor.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  x_train_data_path: [artifacts/data_transformation/fraudulent_transection/X_train.npy, artifacts/data_transformation/default_on_payment/X_train.npy]
  y_train_data_path: [artifacts/data_transformation/fraudulent_transection/y_train.npy, artifacts/data_transformation/default_on_payment/y_train.npy]
  x_val_data_path: [artifacts/data_transformation/fraudulent_transection/X_val.npy, artifacts/data_transformation/default_on_payment/X_val.npy]
  y_val_data_path: [artifacts/data_transformation/fraudulent_transection/y_val.npy, artifacts/data_transformation/default_on_payment/y_val.npy]
  model_name: [fraudulent.joblib, default.joblib]

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: [artifacts/model_trainer/fraudulent.joblib, artifacts/model_trainer/default.joblib]
  x_test_data_path: [artifacts/data_transformation/fraudulent_transection/X_test.npy, artifacts/data_transformation/default_on_payment/X_test.npy]
  y_test_data_path: [artifacts/data_transformation/fraudulent_transection/y_test.npy, artifacts/data_transformation/default_on_payment/y_test.npy]
  evaluation_report: [artifacts/model_evaluation/fraudulent_transection, artifacts/model_evaluation/default_on_payment]